import Head from 'next/head';
import AppNavBar from '../components/AppNavBar';
import AppCardBullets from '../components/AppCardBullets';

export default function Home() {

  const bullets_today = [
    {type: 'event', title: 'Momento síncrono sobre componente react'},
    {type: 'task', title: 'Palavras Chaves - bullet jornal, github issues'}
  ];

  const bullets_tomorrow = [
    {type: 'task', title: 'Priorizar palavras-chaves'},
    {type: 'task', title: 'Pesquisar imagens a partir de palavras-chaves'},
    {type: 'task', title: 'Prototipar UI'}
  ];

  let title = "Meu primeiro WebApp";

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <AppNavBar title={title} />
        <AppCardBullets date={"18/09/2021"} bullets={bullets_today} />
        <AppCardBullets date={"21/09/2021"} bullets={bullets_tomorrow} />
      </main>

    </div>
  )
}